###
POST http://localhost:5002/movies_api/add_movie/kokolusskaa
Content-Type: application/json

{
  "title": "Red",
  "movie_type": "comedy",
  "ratings": 97,
  "duration": 100,
  "age_restriction": 18,
  "description": "great film",
  "cast": "DiCaprio, Joli",
  "genres": "comedy",
  "category": "comedy",
  "production": "great entertainment",
  "country": "UA",
  "is_favourite": "False"
}


###
PUT http://localhost:5002/movies_api/add_to_favourites/Red/kokolusskaa
Content-Type: application/json

###
GET http://localhost:5002/movies_api/favourite_movies/kokolusskaa
Content-Type: application/json


###  вертає лише 1 фільм чому?
GET http://localhost:5002/movies_api/movies/kokolusskaa
Content-Type: application/json


###
GET http://localhost:5002/movies_api/search_movie/Red Notice/kokolusskaa
Content-Type: application/json


###
GET http://localhost:5002/movies_api/trending_now/kokolusskaa
Content-Type: application/json


###
DELETE http://localhost:5002/movies_api/delete_movie/Red/kokolusskaa
Content-Type: application/json

