FROM python:3.8-alpine

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN apk add --no-cache postgresql-libs

RUN apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev

RUN python3 -m pip install -r requirements.txt --no-cache-dir

RUN apk --purge del .build-deps

COPY . /app

ENTRYPOINT [ "python" ]

CMD ["app.py" ]

EXPOSE 5000
