FROM python:3.9-alpine

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN python3 -m pip install -r requirements.txt --no-cache-dir

COPY . /app

ENTRYPOINT [ "python" ]

CMD ["app.py" ]

EXPOSE 5000
